micronaut:
  application:
    name: demo1
tracing:
  zipkin:
    enabled: true
    http:
      url:
      path:
    sampler:
      probability: 1
    supportsJoin: false
codes:
  recursive:
    demo2:
      baseUrl: http://demo2.toddrsharp.com:8080